wakatime:
  secret-api-key: ${WAKATIME_APP_KEY}  # wakatime app key
  proxy-url: ${WAKATIME_PROXY_URL:false} # wakatime接口访问代理地址,例如：socks5://127.0.0.1:1080 或 http://127.0.0.1:1087，请根据实际情况配置
  start-day: ${START_DAY:2016-01-01} # 起始记录时间
  ftqq-key: ${WAKATIME_FTQQ_KEY} # Server酱 SCKEY @see http://sc.ftqq.com，为空表示不发生此类消息通知
  dingding-key: ${wakatime.dingding.key} # 钉钉机器人token，为空表示不发生此类消息通知
  fill-no-data-day: true # 活动图中如果某天没数据，是否要用空数据填充

quarkus:
  swagger-ui:
    always-include: true
  http:
    port: ${SERVER_PORT:3040}

  devservices:
    enabled: false
  datasource:
    devservices:
      enabled: false
    db-kind: mysql
    jdbc:
      url: ${MYSQL_URL}
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USERNAME}
  hibernate-orm:
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  smallrye-health:
    root-path: /actuator/health
  micrometer:
    export:
      prometheus:
        path: /actuator/prometheus
  native:
    debug:
        enabled: true
    additional-build-args:
      - --initialize-at-run-time=jodd.util.RandomString
      - --trace-object-instantiation=java.io.FilePermission