name: ci

on:
  push:
    branches: quarkus

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set docker image name env
        run: echo ::set-env name=DOCKER_IMAGE_NAME::wf2311/wakatime-sync
      -
        name: Set docker image tag env
        run: echo ::set-env name=DOCKER_TAG_VERSION::native-$(echo $GITHUB_RUN_NUMBER)
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_API_KEY }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG_VERSION }}
            ${{ env.DOCKER_IMAGE_NAME }}:latest
