name: quarkus-build

on:
  push:
    branches:
      - quarkus

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      OS: linux
    steps:
      - uses: actions/checkout@v2
      - name: Install graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.1.0'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build native executable
        run: ./mvnw -DskipTests package -Dnative
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_API_KEY }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            wf2311/wakatime-sync:native-0.1
            wf2311/wakatime-sync:latest
      - name: Upload native executable
        id: upload-native-executable
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./target/wakatime-sync-native-0.1-SNAPSHOT-runner
          asset_name: wakatime-sync-native-0.1-SNAPSHOT-runner-linux
          tag: native-0.1-SNAPSHOT
          overwrite: true